### ISSUE TITLE
Json Decoding Failed - inchoo php7 1.06

### ISSUE THREAD

**Issue by HRR1337** [Inchoo/Inchoo_PHP7#75]
Hello,

I have installed an extension that is not working with inchoo php7. I'm using 1.06. And Magento 1.9.2.4

What I have done to make it work:

- installing inchoo 1.06 mod manually 
- testing change to core: 

`$out .= $this->getBlock($callback[0])->$callback[1]();` 

to

`$this->getBlock($callback[0])->{$callback[1]}();`

I can open the extension, though when I want to add a new profile I see the following error:

`a:5:{i:0;s:29:"Decoding failed: Syntax error";i:1;s:2981:"#0 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Helper/Data.php(659): Zend_Json::decode('', 1)
#1 /home/usr/domains/dmn.com/public_html/app/code/local/EcommerceTeam/Dataflow/Model/Profile/Import.php(164): Mage_Core_Helper_Data->jsonDecode(NULL)
#2 /home/usr/domains/dmn.com/public_html/app/code/local/EcommerceTeam/Dataflow/Block/Adminhtml/Profile/Import/Edit/Tab/Mapping.php(33): EcommerceTeam_Dataflow_Model_Profile_Import->getMapping()
#3 /home/usr/domains/dmn.com/public_html/app/design/adminhtml/default/default/template/ecommerceteam/dataflow/import/profile/edit/mapping.phtml(12): EcommerceTeam_Dataflow_Block_Adminhtml_Profile_Import_Edit_Tab_Mapping->getMapping()
#4 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/usr/d...')
#5 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#6 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#7 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#8 /home/usr/domains/dmn.com/public_html/app/code/local/EcommerceTeam/Dataflow/Block/Adminhtml/Profile/Import/Edit/Tabs.php(39): Mage_Core_Block_Abstract->toHtml()
#9 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(293): EcommerceTeam_Dataflow_Block_Adminhtml_Profile_Import_Edit_Tabs->_prepareLayout()
#10 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Inchoo_PHP7_Model_Layout))
#11 /home/usr/domains/dmn.com/public_html/app/code/local/EcommerceTeam/Dataflow/controllers/Adminhtml/Dataflow/Profile/ImportController.php(70): Mage_Core_Model_Layout->createBlock('ecommerceteam_d...')
#12 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): EcommerceTeam_Dataflow_Adminhtml_Dataflow_Profile_ImportController->editAction()
#13 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#14 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /home/usr/domains/dmn.com/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#16 /home/usr/domains/dmn.com/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#17 /home/usr/domains/dmn.com/public_html/index.php(83): Mage::run('', 'store')
#18 {main}";s:3:"url";s:86:"/index.php/beheercdm/dataflow_profile_import/new/key/1b10fb9f764885a4d3d86fefe910a693/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}`

Anyone get an idea how to fix this? (p.s. I also have mailed the guys from the extension, waiting for repley).

Thanks in advance,

HRR

**Comment by HRR1337** [comment]
Extension supplier gave update for php7. Works perfect now.
